// flow-typed signature: c6e293846e74d1507d3096fa1c09a11c
// flow-typed version: <<STUB>>/babelrc-rollup_v3.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babelrc-rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babelrc-rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babelrc-rollup/dist/babelrc-rollup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babelrc-rollup/dist/babelrc-rollup.js' {
  declare module.exports: $Exports<'babelrc-rollup/dist/babelrc-rollup'>;
}
