// flow-typed signature: bac66bc551f1d6633e84c5ac23b2219d
// flow-typed version: <<STUB>>/eslint-plugin-jane_v0.6.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jane'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jane' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jane/prettier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/prettier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jane/rules/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jane/index' {
  declare module.exports: $Exports<'eslint-plugin-jane'>;
}
declare module 'eslint-plugin-jane/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jane'>;
}
declare module 'eslint-plugin-jane/prettier.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/prettier'>;
}
declare module 'eslint-plugin-jane/rules/flow.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/flow'>;
}
declare module 'eslint-plugin-jane/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/index'>;
}
declare module 'eslint-plugin-jane/rules/node.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/node'>;
}
declare module 'eslint-plugin-jane/rules/prettier.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/prettier'>;
}
declare module 'eslint-plugin-jane/rules/react.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/react'>;
}
declare module 'eslint-plugin-jane/rules/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/recommended'>;
}
declare module 'eslint-plugin-jane/rules/style.js' {
  declare module.exports: $Exports<'eslint-plugin-jane/rules/style'>;
}
